# grab the lastest python version
FROM python:latest

# must import the 'server.py' and 'index.html' file.
ADD server.py /server/
ADD index.html /server/

# change base dir to /server
WORKDIR /server/